BEGIN;

INSERT INTO score_definitions (id, code, name, description, scale_min, scale_max, kind) VALUES ('65bf8ce6-9077-549a-931f-46e5e33c4978', 'promise_gap', 'Promise Gap', 'How much of the theoretical promise remains unrealized. One of the site''s most important numbers. Formula: world_impact_potential - reality', -10, 10, 'derived') ON CONFLICT (id) DO NOTHING;
INSERT INTO score_definitions (id, code, name, description, scale_min, scale_max, kind) VALUES ('98a62fca-dbf9-5b3d-9f6d-b5a7bb14a7fa', 'build_gap', 'Build Gap', 'Positive: developers building faster than utility arrives. Promising or concerning depending on trajectory and Prove-It Age. Formula: development - reality', -10, 10, 'derived') ON CONFLICT (id) DO NOTHING;
INSERT INTO score_definitions (id, code, name, description, scale_min, scale_max, kind) VALUES ('e4dc08a3-6efd-51ff-a8b8-fac74f2043f0', 'hype_gap', 'Hype Gap', 'Attention scoring is Phase 2 (no reliable source in v0.1). Formula: attention - reality', -10, 10, 'derived') ON CONFLICT (id) DO NOTHING;
INSERT INTO score_definitions (id, code, name, description, scale_min, scale_max, kind) VALUES ('3769e046-20e2-5937-89d0-e81f9983e863', 'belief_gap', 'Belief Gap', 'No community layer in v0.1 (Phase 3). Formula: community_reality - algorithmic_reality', -10, 10, 'derived') ON CONFLICT (id) DO NOTHING;
INSERT INTO score_definitions (id, code, name, description, scale_min, scale_max, kind) VALUES ('7b134f5e-1f68-54b0-b005-2e2263045672', 'potential_outlook', 'Potential Outlook', 'Forward-looking, but NOT a probability and NOT a price prediction — uncalibrated until historical backtesting exists (same rule as Execution Evidence). Reads as: of the promise not yet realized, how much does current execution support capturing? Floored at 0: a negative promise gap means the thesis is already exceeded, leaving no unrealized promise to capture. Formula: clamp(max(promise_gap, 0) × (execution_evidence / 10), 0, 10)', 0, 10, 'derived') ON CONFLICT (id) DO NOTHING;

COMMIT;
