import { DOMParser } from "linkedom";
import { isSocialSlug, isStockSlug, SOCIAL_SOURCES, STOCK_SOURCES } from "./social";
import type { MentionFeed, NewsMention } from "./hype-mentions";

// Feed search can match site navigation rather than the story itself.
const HEADLINE_MATCH: Record<string, RegExp> = {
  btc: /\b(bitcoin|btc)\b/i, eth: /\b(ethereum|ether|eth)\b/i,
  xrp: /\b(xrp|ripple)\b/i, sol: /\bsolana\b/i,
  link: /\bchainlink\b/i, avax: /\b(avax|avalanche)\b/i,
  dash: /\bdash\b/i, bat: /\bbasic attention token\b|\bbrave (browser|wallet|rewards)\b|\bBAT (token|crypto)\b/i,
  ada: /\\b(Cardano|ADA)\\b/i,
  usdt: /\\b(Tether|USDT)\\b/i,
  bnb: /\\b(BNB|BNB)\\b/i,
  usdc: /\\b(USD\ Coin|USDC)\\b/i,
  trx: /\\b(TRON|TRX)\\b/i,
  zec: /\\b(Zcash|ZEC)\\b/i,
  hype: /\\b(Hyperliquid|HYPE)\\b/i,
  doge: /\\b(Dogecoin|DOGE)\\b/i,
  xmr: /\\b(Monero|XMR)\\b/i,
  rain: /\\b(Rain|RAIN)\\b/i,
  usds: /\\b(USDS|USDS)\\b/i,
  leo: /\\b(LEO\ Token|LEO)\\b/i,
  xlm: /\\b(Stellar|XLM)\\b/i,
  figr_heloc: /\\b(Figure\ Heloc)\\b/i,
  wbt: /\\b(WhiteBIT\ Coin|WBT)\\b/i,
  near: /\\b(NEAR\ Protocol|NEAR)\\b/i,
  bch: /\\b(Bitcoin\ Cash|BCH)\\b/i,
  uni: /\\b(Uniswap|UNI)\\b/i,
  ltc: /\\b(Litecoin|LTC)\\b/i,
  canton: /\\b(Canton|CC)\\b/i,
  hbar: /\\b(Hedera|HBAR)\\b/i,
  usde: /\\b(Ethena\ USDe|USDE)\\b/i,
  sui: /\\b(Sui|SUI)\\b/i,
  ton: /\\b(Gram\ \(prev\.\ Toncoin\)|GRAM)\\b/i,
  syrup: /\\b(Maple\ Finance|SYRUP)\\b/i,
  rune: /\\b(THORChain|RUNE)\\b/i,
  akt: /\\b(Akash\ Network|AKT)\\b/i,
  eigen: /\\b(EigenCloud\ \(prev\.\ EigenLayer\)|EIGEN)\\b/i,
  twt: /\\b(Trust\ Wallet|TWT)\\b/i,
  comp: /\\b(Compound|COMP)\\b/i,
  kaia: /\\b(Kaia|KAIA)\\b/i,
  imx: /\\b(Immutable|IMX)\\b/i,
  snx: /\\b(Synthetix|SNX)\\b/i,
  1inch: /\\b(1INCH|1INCH)\\b/i,
  tao: /\\b(Bittensor|TAO)\\b/i,
  geod: /\\b(Geodnet|GEOD)\\b/i,
  dot: /\\b(Polkadot|DOT)\\b/i,
  om: /\\b(MANTRA|OM)\\b/i,
  pepe: /\\b(Pepe|PEPE)\\b/i,
  ondo: /\\b(Ondo|ONDO)\\b/i,
  render: /\\b(Render|RENDER)\\b/i,
  arb: /\\b(Arbitrum|ARB)\\b/i,
  kas: /\\b(Kaspa|KAS)\\b/i,
  aave: /\\b(Aave|AAVE)\\b/i,
  atom: /\\b(Cosmos\ Hub|ATOM)\\b/i,
  algo: /\\b(Algorand|ALGO)\\b/i,
  fet: /\\b(Artificial\ Superintelligence\ Alliance|FET)\\b/i,
  jup: /\\b(Jupiter|JUP)\\b/i,
  sei: /\\b(Sei|SEI)\\b/i,
  floki: /\\b(FLOKI|FLOKI)\\b/i,
  bonk: /\\b(Bonk|BONK)\\b/i,
  strk: /\\b(Starknet|STRK)\\b/i,
  inj: /\\b(Injective|INJ)\\b/i,
  op: /\\b(Optimism|OP)\\b/i,
  grt: /\\b(The\ Graph|GRT)\\b/i,
  qnt: /\\b(Quant|QNT)\\b/i,
  ldo: /\\b(Lido\ DAO|LDO)\\b/i,
  ousd: /\\b(Ondo\ USD\ Yield|OUSD)\\b/i,
  gala: /\\b(GALA|GALA)\\b/i,
  sky: /\\b(Sky|SKY)\\b/i,
  pengu: /\\b(Pudgy\ Penguins|PENGU)\\b/i,
  fil: /\\b(Filecoin|FIL)\\b/i,
  xaut: /\\b(Tether\ Gold|XAUT)\\b/i,
  wld: /\\b(Worldcoin|WLD)\\b/i,
  crv: /\\b(Curve\ DAO|CRV)\\b/i,
  pyth: /\\b(Pyth\ Network|PYTH)\\b/i,
  hsol: /\\b(Helius\ Staked\ SOL|HSOL)\\b/i,
  jto: /\\b(Jito|JTO)\\b/i,
  xtz: /\\b(Tezos|XTZ)\\b/i,
  bgb: /\\b(Bitget\ Token|BGB)\\b/i,
  jasmy: /\\b(JasmyCoin|JASMY)\\b/i,
  cfx: /\\b(Conflux|CFX)\\b/i,
  cake: /\\b(PancakeSwap|CAKE)\\b/i,
  nexo: /\\b(NEXO|NEXO)\\b/i,
  fartcoin: /\\b(Fartcoin)\\b/i,
  okb: /\\b(OKB|OKB)\\b/i,
  tia: /\\b(Celestia|TIA)\\b/i,
  vet: /\\b(VeChain|VET)\\b/i,
  eos: /\\b(EOS|EOS)\\b/i,
  s: /\\b(Sonic)\\b/i,
  iota: /\\b(IOTA|IOTA)\\b/i,
  xdc: /\\b(XDC\ Network|XDC)\\b/i,
  ath: /\\b(Aethir|ATH)\\b/i,
  wif: /\\b(dogwifhat|WIF)\\b/i,
  hnt: /\\b(Helium|HNT)\\b/i,
  stx: /\\b(Stacks|STX)\\b/i,
  kava: /\\b(Kava|KAVA)\\b/i,
  mnt: /\\b(Mantle|MNT)\\b/i,
  apt: /\\b(Aptos|APT)\\b/i,
  pol: /\\b(Polygon|POL)\\b/i,
  ftm: /\\b(Fantom|FTM)\\b/i,
  cro: /\\b(Cronos|CRO)\\b/i,
  egld: /\\b(MultiversX|EGLD)\\b/i,
  flow: /\\b(Flow|FLOW)\\b/i,
  chz: /\\b(Chiliz|CHZ)\\b/i,
  a7a5: /\\b(A7A5|A7A5)\\b/i,
  xpl: /\\b(Plasma|XPL)\\b/i,
  pendle: /\\b(Pendle|PENDLE)\\b/i,
  drv: /\\b(Derive|DRV)\\b/i,
  spx: /\\b(SPX6900|SPX)\\b/i,
  bsv: /\\b(Bitcoin\ SV|BSV)\\b/i,
  mon: /\\b(Monad|MON)\\b/i,
  ff: /\\b(Falcon\ Finance|FF)\\b/i,
  btt: /\\b(BitTorrent|BTT)\\b/i,
  pieverse: /\\b(Pieverse)\\b/i,
  kite: /\\b(Kite|KITE)\\b/i,
  ub: /\\b(Unibase|UB)\\b/i,
  usdai: /\\b(USDai|USDAI)\\b/i,
  sofid: /\\b(SoFiUSD|SOFID)\\b/i,
  prl: /\\b(Pearl|PRL)\\b/i,
  sun: /\\b(Sun\ Token|SUN)\\b/i,
  hash: /\\b(Provenance\ Blockchain|HASH)\\b/i,
  jtrsy: /\\b(Janus\ Henderson\ Anemoy\ Treasury\ Fund|JTRSY)\\b/i,
  fdusd: /\\b(First\ Digital\ USD|FDUSD)\\b/i,
  ousg: /\\b(Ondo\ Short\-Term\ U\.S\.\ Government\ Bond\ Fund|OUSG)\\b/i,
  dcr: /\\b(Decred|DCR)\\b/i,
  apxusd: /\\b(apxUSD|APXUSD)\\b/i,
  gno: /\\b(Gnosis|GNO)\\b/i,
  bp: /\\b(Backpack|BP)\\b/i,
  ohm: /\\b(Olympus|OHM)\\b/i,
  reusd: /\\b(Re\ Protocol\ reUSD|REUSD)\\b/i,
  lunc: /\\b(Terra\ Luna\ Classic|LUNC)\\b/i,
  ar: /\\b(Arweave|AR)\\b/i,
  ens: /\\b(Ethereum\ Name\ Service|ENS)\\b/i,
  pons: /\\b(Pons|PONS)\\b/i,
  apepe: /\\b(Ape\ and\ Pepe|APEPE)\\b/i,
  zbcn: /\\b(Zebec\ Network|ZBCN)\\b/i,
  useless: /\\b(Useless\ Coin)\\b/i,
  axs: /\\b(Axie\ Infinity|AXS)\\b/i,
  nft: /\\b(AINFT|NFT)\\b/i,
  2z: /\\b(DoubleZero|2Z)\\b/i,
  sand: /\\b(The\ Sandbox|SAND)\\b/i,
  crvusd: /\\b(crvUSD|CRVUSD)\\b/i,
  kmno: /\\b(Kamino|KMNO)\\b/i,
  theta: /\\b(Theta\ Network|THETA)\\b/i,
  cards: /\\b(Collector\ Crypt|CARDS)\\b/i,
  kag: /\\b(Kinesis\ Silver|KAG)\\b/i,
  koge: /\\b(KOGE|KOGE)\\b/i,
  ausd: /\\b(AUSD|AUSD)\\b/i,
  zama: /\\b(Zama|ZAMA)\\b/i,
  frax: /\\b(Legacy\ Frax\ Dollar|FRAX)\\b/i,
  shfl: /\\b(Shuffle|SHFL)\\b/i,
  usx: /\\b(USX|USX)\\b/i,
  safo: /\\b(Spiko\ Amundi\ Overnight\ Swap\ Fund|SAFO)\\b/i,
  cvx: /\\b(Convex\ Finance|CVX)\\b/i,
  mina: /\\b(Mina\ Protocol|MINA)\\b/i,
  mana: /\\b(Decentraland|MANA)\\b/i,
  pc0000031: /\\b(Tradable\ NA\ Rent\ Financing\ Platform\ SSTN)\\b/i,
  grx: /\\b(GRX\ Chain|GRX)\\b/i,
  xcn: /\\b(Onyxcoin|XCN)\\b/i,
  eurcv: /\\b(EUR\ CoinVertible|EURCV)\\b/i,
  usat: /\\b(USAT|USAT)\\b/i,
  neo: /\\b(NEO|NEO)\\b/i,
  internet-computer: /\\b(Internet\ Computer|ICP)\\b/i,
  berachain: /\\b(Berachain|BERA)\\b/i,
  harmony: /\\b(Harmony|ONE)\\b/i,
  oasis-network: /\\b(Oasis\ Network|ROSE)\\b/i,
  zilliqa: /\\b(Zilliqa|ZIL)\\b/i,
  waves: /\\b(Waves|WAVES)\\b/i,
  kadena: /\\b(Kadena|KDA)\\b/i,
  nervos-network: /\\b(Nervos\ Network|CKB)\\b/i,
  radix: /\\b(Radix|XRD)\\b/i,
  zksync: /\\b(ZKsync|ZK)\\b/i,
  scroll: /\\b(Scroll|SCR)\\b/i,
  blast: /\\b(Blast|BLAST)\\b/i,
  dydx: /\\b(dYdX|DYDX)\\b/i,
  taiko: /\\b(Taiko|TAIKO)\\b/i,
  metis: /\\b(Metis|METIS)\\b/i,
  movement: /\\b(Movement|MOVE)\\b/i,
  fuel: /\\b(Fuel|FUEL)\\b/i,
  aevo: /\\b(Aevo|AEVO)\\b/i,
  base: /\\b(Base|BASE)\\b/i,
  balancer: /\\b(Balancer|BAL)\\b/i,
  sushiswap: /\\b(SushiSwap|SUSHI)\\b/i,
  yearn-finance: /\\b(Yearn|YFI)\\b/i,
  gmx: /\\b(GMX|GMX)\\b/i,
  raydium: /\\b(Raydium|RAY)\\b/i,
  orca: /\\b(Orca|ORCA)\\b/i,
  morpho: /\\b(Morpho|MORPHO)\\b/i,
  liquity: /\\b(Liquity|LQTY)\\b/i,
  rocket-pool: /\\b(Rocket\ Pool|RPL)\\b/i,
  ethena: /\\b(Ethena|ENA)\\b/i,
  etherfi: /\\b(Ether\.fi|ETHFI)\\b/i,
  renzo: /\\b(Renzo|REZ)\\b/i,
  marinade: /\\b(Marinade|MNDE)\\b/i,
  goldfinch: /\\b(Goldfinch|GFI)\\b/i,
  centrifuge: /\\b(Centrifuge|CFG)\\b/i,
  band: /\\b(Band\ Protocol|BAND)\\b/i,
  api3: /\\b(API3|API3)\\b/i,
  storj: /\\b(Storj|STORJ)\\b/i,
  siacoin: /\\b(Siacoin|SC)\\b/i,
  livepeer: /\\b(Livepeer|LPT)\\b/i,
  ocean: /\\b(Ocean\ Protocol|OCEAN)\\b/i,
  covalent: /\\b(Covalent|CQT)\\b/i,
  ankr: /\\b(Ankr|ANKR)\\b/i,
  pocket: /\\b(Pocket\ Network|POKT)\\b/i,
  tellor: /\\b(Tellor|TRB)\\b/i,
  layerzero: /\\b(LayerZero|ZRO)\\b/i,
  wormhole: /\\b(Wormhole)\\b/i,
  axelar: /\\b(Axelar|AXL)\\b/i,
  across: /\\b(Across\ Protocol|ACX)\\b/i,
  synapse: /\\b(Synapse\ Protocol|SYN)\\b/i,
  stargate: /\\b(Stargate\ Finance|STG)\\b/i,
  aleo: /\\b(Aleo|ALEO)\\b/i,
  ironfish: /\\b(Iron\ Fish|IRON)\\b/i,
  hivemapper: /\\b(Hivemapper|HONEY)\\b/i,
  ionet: /\\b(io\.net|IO)\\b/i,
  ronin: /\\b(Ronin|RON)\\b/i,
  enjin: /\\b(Enjin|ENJ)\\b/i,
  mythos: /\\b(Mythos|MYTH)\\b/i,
  beam: /\\b(Beam|BEAM)\\b/i,
  xai: /\\b(Xai|XAI)\\b/i,
  treasure: /\\b(Treasure|MAGIC)\\b/i,
  blur: /\\b(Blur|BLUR)\\b/i,
  illuvium: /\\b(Illuvium|ILV)\\b/i,
  wax: /\\b(WAX|WAXP)\\b/i,
  echelon-prime: /\\b(Echelon\ Prime|PRIME)\\b/i,
  osmosis: /\\b(Osmosis|OSMO)\\b/i,
  kujira: /\\b(Kujira|KUJI)\\b/i,
  neutron: /\\b(Neutron|NTRN)\\b/i,
  stride: /\\b(Stride|STRD)\\b/i,
  secret: /\\b(Secret\ Network|SCRT)\\b/i,
  juno: /\\b(Juno|JUNO)\\b/i,
  babylon: /\\b(Babylon|BABY)\\b/i,
  mars: /\\b(Mars\ Protocol|MARS)\\b/i,
  star-atlas: /\\b(Star\ Atlas|ATLAS)\\b/i,
  step-finance: /\\b(Step\ Finance|STEP)\\b/i,
  mango-markets: /\\b(Mango\ Markets|MNGO)\\b/i,
  drift-protocol: /\\b(Drift\ Protocol|DRIFT)\\b/i,
  tensor: /\\b(Tensor|TNSR)\\b/i,
  sanctum: /\\b(Sanctum|SANC)\\b/i,
  singularitynet: /\\b(SingularityNET|AGIX)\\b/i,
  dimo: /\\b(DIMO|DIMO)\\b/i,
  peaq: /\\b(peaq|PEAQ)\\b/i,
  numerai: /\\b(Numerai|NMR)\\b/i,
  virtuals-protocol: /\\b(Virtuals\ Protocol)\\b/i,
  astar: /\\b(Astar|ASTR)\\b/i,
  moonbeam: /\\b(Moonbeam|GLMR)\\b/i,
  celo: /\\b(Celo|CELO)\\b/i,
  sommelier: /\\b(Sommelier|SOMM)\\b/i,
  beefy: /\\b(Beefy\ Finance|BIFI)\\b/i,
  vertex: /\\b(Vertex\ Protocol|VRTX)\\b/i,
  dia: /\\b(DIA|DIA)\\b/i,
  subsquid: /\\b(Subsquid|SQD)\\b/i,
  supra: /\\b(Supra|SUPRA)\\b/i,
  railgun: /\\b(Railgun|RAIL)\\b/i,
  allora: /\\b(Allora\ Network|ALLO)\\b/i,
  grass: /\\b(Grass|GRASS)\\b/i,
  nosana: /\\b(Nosana|NOS)\\b/i,
  weatherxm: /\\b(WeatherXM|WXM)\\b/i,
  wingbits: /\\b(Wingbits|WINGS)\\b/i,
  plume: /\\b(Plume\ Network|PLUME)\\b/i,
  debridge: /\\b(deBridge|DBR)\\b/i,
  swell: /\\b(Swell\ Network|SWELL)\\b/i,
  silencio: /\\b(Silencio|SLC)\\b/i,
  natix: /\\b(NATIX\ Network|NATIX)\\b/i,
};

function safeUrl(value: string | null | undefined): string | null {
  try {
    const url = new URL(value ?? "");
    if (!["https:", "http:"].includes(url.protocol) || url.username || url.password) return null;
    url.hash = "";
    return url.href;
  } catch { return null; }
}

export function newsFeedUrl(slug: string): string {
  const query = isSocialSlug(slug)
    ? SOCIAL_SOURCES[slug].newsQuery
    : isStockSlug(slug)
      ? STOCK_SOURCES[slug].newsQuery
      : null;
  if (!query) throw new Error("Unknown project");
  const url = new URL("https://news.google.com/rss/search");
  url.search = new URLSearchParams({ q: query + " when:7d", hl: "en-US", gl: "US", ceid: "US:en" }).toString();
  return url.href;
}

/** Count actual items, not channel dates; never interpret feed HTML as markup. */
export function parseNewsFeed(xml: string, slug: string, now = new Date()): MentionFeed {
  const source_url = newsFeedUrl(slug);
  if (xml.length > 2_000_000 || /<!DOCTYPE|<!ENTITY/i.test(xml)) throw new Error("Invalid news feed");
  const doc = new DOMParser().parseFromString(xml, "text/xml");
  if (!doc.querySelector("rss > channel")) throw new Error("Invalid news feed");
  const end = now.getTime();
  const start = end - 7 * 86_400_000;
  const items = [...doc.querySelectorAll("item")];
  const articles: NewsMention[] = [];
  const seen = new Set<string>();
  for (const item of items) {
    const url = safeUrl(item.querySelector("link")?.textContent?.trim());
    const published = Date.parse(item.querySelector("pubDate")?.textContent ?? "");
    let title = item.querySelector("title")?.textContent?.trim() ?? "";
    if (!url || !title || !Number.isFinite(published) || published < start || published > end || seen.has(url)) continue;
    const source = item.querySelector("source");
    const publisher = source?.textContent?.trim() || "Unknown publisher";
    // Google appends the publisher to the title; it is already shown separately.
    const suffix = " - " + publisher;
    if (title.endsWith(suffix)) title = title.slice(0, -suffix.length);
    if (!HEADLINE_MATCH[slug].test(title)) continue;
    seen.add(url);
    articles.push({ url, title, publisher, publisher_url: safeUrl(source?.getAttribute("url")), published_at: new Date(published).toISOString() });
  }
  articles.sort((a, b) => b.published_at.localeCompare(a.published_at) || a.url.localeCompare(b.url));
  return { slug, provider: "Google News RSS", fetched_at: now.toISOString(), window_start: new Date(start).toISOString(), window_end: now.toISOString(), source_url, articles, feed_items: items.length };
}

export async function fetchNewsMentions(slug: string, fetcher: typeof fetch = fetch): Promise<MentionFeed> {
  const response = await fetcher(newsFeedUrl(slug), {
    headers: { Accept: "application/rss+xml, application/xml, text/xml" },
    signal: AbortSignal.timeout(12_000), cache: "no-store", redirect: "error",
  });
  if (!response.ok) throw new Error("News provider unavailable");
  return parseNewsFeed(await response.text(), slug);
}
