/** Local captured artifact only: no environment loading, database writes or provider calls. */
import { readFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { CATEGORIES } from '../data/atlas-taxonomy';
import { adaptAtlas } from '../src/lib/atlas/adapter';
import { calibrate, formatStateBreakdown, parseDraftWeights } from './lib/ranking-calibration';

const artifactPath = '../../db/seed/heart-runs/hearts-promise-2026-09-26.json';
const draftPath = '../../docs/tasks/2026-09-26-verdict-weights-draft.md';
const artifactText = readFileSync(new URL(artifactPath, import.meta.url), 'utf8');
const draftText = readFileSync(new URL(draftPath, import.meta.url), 'utf8');
const artifact = JSON.parse(artifactText);
if (artifact.schema_version !== 3 || artifact.review_status !== 'published' || !artifact.run_key) throw new Error('Expected captured published v3 artifact');
const data = adaptAtlas({
  run: { id: artifact.run_key, as_of: artifact.as_of, methodology: artifact.methodology, review_status: artifact.review_status },
  projects: artifact.projects.map((project: Record<string, unknown>) => ({ ...project, run_id: artifact.run_key, methodology: artifact.methodology })),
});
if (!data) throw new Error('Published artifact unavailable');
const result = calibrate(data, parseDraftWeights(draftText, data.nodes));
const sha256 = (text: string) => createHash('sha256').update(text).digest('hex');
const report = { ...result, inputs: {
  ledger: { path: artifactPath.replace('../../', ''), sha256: sha256(artifactText) },
  weights: { path: draftPath.replace('../../', ''), sha256: sha256(draftText), author: 'Habib (Muse)', review: 'unreviewed draft' },
  categories: { path: 'app/data/atlas-assignments.ts', sha256: sha256(readFileSync(new URL('../data/atlas-assignments.ts', import.meta.url), 'utf8')) },
} };
if (process.argv.slice(2).some(arg => arg !== '--json')) throw new Error('Usage: calibrate-ranking.ts [--json]');
if (process.argv.includes('--json')) {
  console.log(JSON.stringify(report, null, 2));
} else {
  const pct = (value: number | null) => value == null ? 'Unavailable' : `${(100 * value).toFixed(1)}%`;
  const range = (values: number[]) => !values.length ? 'Unranked' : `${Math.min(...values)}–${Math.max(...values)}`;
  const out = [
    '# Ranking calibration: captured ledger and draft weights', '',
    '**Diagnostic only. These are not approved ratings, economic-impact scores or valuation estimates.**', '',
    `Generated by \`npm run ranking:calibrate\` from \`${data.dataRevision}\`, as of ${data.asOf}.`,
    'No live data was fetched. Published states are held fixed; this exercise does not validate the underlying research.', '',
    `Coverage: ${result.coverage.promises} promises, ${result.coverage.projects} projects, ${result.coverage.draftWeights} draft weights.`,
    `Missing weights: ${result.coverage.missingWeightIds.length}. No substitute weights are assigned. BTC stays outside comparative verdicts under the Genesis decision.`, '',
    'Formula: kept assigned weight / all assigned weight in one primary category. Open and unknown remain in the denominator without being called failures. Lapsed and retired remain separately labeled v3 states; this is not a v4 restatement.', '',
    `Tested ratios (low:middle:high tier): ${result.profiles.map(profile => profile.id).join(', ')}.`,
    'Equal weights are the baseline; 1:2:3 is the required less-steep comparison; 1:2:4 replays Muse’s draft; 1:2:8 is a stress test. The ranges describe only these parameter probes, not confidence intervals. All category figures are conditional on unresolved admission, attribution and source issues.', '',
    '## Category sensitivity', '',
    'Each project occupies one row per primary category. Secondary tags never add weight. Rank ranges exclude BTC, Unclassified, missing-weight scopes and scopes without recorded resolved outcomes. A small promise sample is not evidence of broad market leadership.', '',
    'Recorded states show promise counts, with 1:2:4 draft weights in parentheses. States with zero records are omitted. Open, in progress, unknown, lapsed and retired remain separate; equal kept shares do not imply equal outcome coverage. Missing weights stay unavailable.', '',
  ];
  for (const category of CATEGORIES) {
    out.push(`### ${category.label}`, '', '| Project | Recorded states (draft weight) | Equal | Less steep 1:2:3 | Draft 1:2:4 | Stress 1:2:8 | Tested rank range |', '|---|---|---:|---:|---:|---:|---:|');
    for (const scope of result.scopes.filter(scope => scope.category === category.id)) {
      const value = (id: string) => scope.comparison === 'no-resolved-outcomes' ? 'Unresolved' : pct(scope.profiles[id].keptShare);
      out.push(`| ${scope.project.toUpperCase()} | ${formatStateBreakdown(scope)} | ${value('1:1:1')} | ${value('1:2:3')} | ${value('1:2:4')} | ${value('1:2:8')} | ${range(Object.values(scope.profiles).flatMap(value => value.rank == null ? [] : [value.rank]))} |`);
    }
    out.push('');
  }
  out.push('## Claims with high influence', '',
    'These are draft tier-4 or ledger-core claims, not new judgments. “Correction exposure” is the maximum percentage-point movement from changing this one claim’s kept/non-kept credit at fixed 1:2:4 weights in its primary category. It is not a recommended regrade. Tier 4 does not change the ledger core flag.', '',
    '| Promise | Category | Recorded state | Ledger core | Draft tier | Correction exposure |', '|---|---|---|---|---:|---:|');
  for (const claim of report.reviewClaims) {
    out.push(`| ${claim.lineage} | ${claim.category} | ${claim.state} | ${claim.core ? 'Yes' : 'No'} | ${claim.draftTier ?? 'Missing'} | ${claim.maxCorrectionPoints == null ? 'Unavailable' : `${claim.maxCorrectionPoints.toFixed(1)} pp`} |`);
  }
  out.push('', '## Data quality', '', '| Flag | Promises |', '|---|---:|');
  for (const [flag, count] of Object.entries(result.coverage.qualityFlags)) out.push(`| ${flag} | ${count} |`);
  out.push('', 'Usage, economic benefit, token attribution and elapsed-time outcomes are not supplied by this artifact. No usage or impact ranking is calculated.', '',
    '## Reproduction', '', `Methodology: ${data.methodologyVersion}. Taxonomy: ${data.taxonomyVersion}. Assignments: ${data.assignmentVersion}.`, '',
    'Run from `app/`: `node --import tsx scripts/calibrate-ranking.ts` (Markdown) or append `--json` for all state weights, exact fractions and ranks. This command writes only to stdout.', '',
    '| Input | SHA-256 |', '|---|---|');
  for (const input of Object.values(report.inputs)) out.push(`| ${input.path} | ${input.sha256} |`);
  console.log(out.join('\n'));
}
